participants:

    Solid:
        interfaces:
        - nodes-mesh: Solid-Mesh
          patch: interface
          read-data: [Force]
          write-data: [Displacement]
          
precice-config-file: ../precice-config.xml
